In [1]:
import torch

In [21]:
test_1 = torch.tensor([[[1, 2, 3, 4]]])
test_2 = torch.tensor([[[5, 6, 7, 8]]])

test_3 = torch.tensor([[1., 2, 3, 4],[5, 6, 7, 8]])

In [13]:
flatten = torch.nn.Flatten((1, 4))
adaptive = torch.nn.AdaptiveAvgPool2d((1, 4))

In [22]:
output = torch.cat((test_1, test_2), dim=-1)

In [23]:
output

tensor([[[1, 2, 3, 4, 5, 6, 7, 8]]])

In [17]:
output2 = adaptive(test_3.unsqueeze(dim=0))

In [18]:
output2

tensor([[[3., 4., 5., 6.]]])

In [20]:
torch.stack((test_1, test_2))

tensor([[[1, 2, 3, 4]],

        [[5, 6, 7, 8]]])